---
provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags

verifier: inspec

suites:
  - name: default
    run_list:
      - recipe[osl-keepalived::default]
  - name: haproxy_osuosl
    run_list:
      - recipe[keepalived_test::eth1]
      - recipe[keepalived_test::hostname]
      - recipe[osl-keepalived::haproxy_osuosl]
    attributes:
      osl-keepalived:
         haproxy:
            interface: 'eth1'
      keepalived_test:
        fqdn: lb1.osuosl.org
        eth1:
          ipv4: 140.211.9.50/24
          ipv6: 2605:bc80:3010:104::8cd3:935/64
  - name: haproxy_phpbb
    run_list:
      - recipe[keepalived_test::hostname]
      - recipe[osl-keepalived::haproxy_phpbb]
    attributes:
      keepalived_test:
        fqdn: lb1.phpbb.org
  - name: mysql2
    run_list:
      - recipe[keepalived_test::hostname]
      - recipe[keepalived_test::eth1]
      - recipe[osl-keepalived::mysql2]
    attributes:
      keepalived_test:
        fqdn: mysql3.osuosl.org
  - name: multi-node
    driver:
      name: terraform
      command_timeout: 1800
    provisioner: terraform
    verifier:
      name: terraform
      systems:
        - name: node1
          backend: ssh
          hosts_output: node1
          sudo: true
          user: centos
          controls:
            - all
            - node1
          hostnames: node1
        - name: node2
          backend: ssh
          hosts_output: node2
          sudo: true
          user: centos
          controls:
            - all
            - node2
          hostnames: node2
