---
suites:
  - name: default
    run_list:
      - recipe[osl-keepalived::default]
  - name: haproxy_osuosl
    run_list:
      - recipe[osl-keepalived::haproxy_osuosl]
    attributes:
      osl-keepalived:
        haproxy-osuosl:
          auth_pass: 'foobar'
  - name: haproxy_phpbb
    run_list:
      - recipe[osl-keepalived::haproxy_phpbb]
    attributes:
      osl-keepalived:
        haproxy-phpbb:
          auth_pass: 'foobar'
