---
provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags

suites:
  - name: default
    run_list:
      - recipe[osl-keepalived::default]
  - name: haproxy_osuosl
    run_list:
      - recipe[keepalived_test::hostname]
      - recipe[osl-keepalived::haproxy_osuosl]
    attributes:
      keepalived_test:
        fqdn: lb1.osuosl.org
  - name: haproxy_phpbb
    run_list:
      - recipe[keepalived_test::hostname]
      - recipe[osl-keepalived::haproxy_phpbb]
    attributes:
      keepalived_test:
        fqdn: lb1.phpbb.org
  - name: mysql2
    run_list:
      - recipe[keepalived_test::hostname]
      - recipe[keepalived_test::eth1]
      - recipe[osl-keepalived::mysql2]
    attributes:
      keepalived_test:
        fqdn: mysql3.osuosl.org
