---
suites:
  - name: default
    run_list:
      - recipe[osl-keepalived::default]
  - name: haproxy_osuosl
    run_list:
      - recipe[osl-keepalived::haproxy_osuosl]
    attributes:
      osl-keepalived:
        haproxy-osuosl:
          master: true
          auth_pass: 'foobar'
