AllCops:
  TargetChefVersion: 16.latest
  Exclude:
    - 'cookbooks/**/*'
ChefModernize/FoodcriticComments:
  Enabled: true
ChefStyle/CopyrightCommentFormat:
  Enabled: true
Style/RegexpLiteral:
  EnforcedStyle: mixed
