name             'keepalived_test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures keepalived_test'
long_description ''
version          '0.1.0'
depends          'base'
depends          'osl-keepalived'
depends          'ucarp'
